Convert module role hats to mutable
Hats-Protocol/allowlist-eligibility pull request #1
Opened 2024-05-11 16:06 UTC by spengrah

Converts ownerHat and arbitratorHat from immutable "constants" to mutable storage values. 

The reason to do this is that this module is stateful, which adds friction to migrating to a new instance in order to update owner or arbitrator roles.

there are two primary benefits of immutable config on modules
1. simple to understand when/how they can be updated, ie by an admin of the hat as long as the hat is mutable
2. some gas savings by using immutable values instead of storage reads

2024-05-11 19:27 UTC, spengrah commented
@gershido do we need `_setup()` to emit events for the owner and arbitrator hats in order to track these authorities in the ancillary subgaph?

2024-05-12 11:58 UTC, gershido requested changes
In addition to the comments, the rest of the functions documentation includes still the previous names - `OWNER_HAT` and `ARBITRATOR_HAT`

2024-05-12 11:58 UTC, gershido commented on src/AllowlistEligibility.sol
> +   * @dev Only callable by a wearer of the current arbitratorHat, and only if the target hat is mutable
Documentation fix: "ownerHat" instead of "arbitratorHat". Or is the intention here is to provide the permission to the arbitrator?

2024-05-12 11:58 UTC, gershido commented on src/AllowlistEligibility.sol
> +
The functions visibility is accidentally `public`

2024-05-12 11:58 UTC, gershido commented on README.md
> +- Wearer(s) of the `arbitrator` can manually put an account in bad standing and burn their hat `setStandingForAccountAndBurnHat()`.
`arbitratorHat` instead of `arbitrator`

2024-05-12 11:58 UTC, gershido commented on README.md
> +- Wearer(s) of the `arbitrator` can simply set the standing of account(s) by calling `setStandingForAccount()` or `setStandingForAccounts()`.
`arbitratorHat` instead of `arbitrator`

2024-05-12 11:58 UTC, gershido commented on README.md
> +This module sets up a simple allowlist to determine eligibility for a hat. For a given account (i.e., potential hat wearer), the allowlist stores values for that account's eligibility and standing fo
`arbitratorHat` instead of `arbitrator`

2024-05-12 18:56 UTC, gershido approved these changes
lgtm

2024-05-13 13:49 UTC, merged